apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: vault-operator
rules:

- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "update", "delete", "patch"]

- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list", "create", "update", "delete", "patch"]

- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "watch", "list", "create", "update", "delete", "patch"]

- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "list", "create", "update", "delete", "patch"]

- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]  

- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
  
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]

- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

- apiGroups: ["apps"]
  resourceNames: ["vault-operator"]
  resources: ["deployments/finalizers"]
  verbs: ["update"]

- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

- apiGroups: ["charts.helm.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

