apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vault-operator
spec:
  selector:
    matchLabels:
      name: vault-operator
  endpoints:
    - port: http-metrics
      scheme: http
      path: /metrics